meta_product_name: "Kyoro"
meta_title: "Kyoro - Keeping your team together"
meta_description: "Kyoro is a management tool that helps your team stay connected through Slack integration and analysis - a quick way to check how your team is doing so that you can meet their needs. Don't let the distance keep your team from feeling connected."
meta_image: "remote-work.jpg"
